import { User, Project, OpenSides, StallType, IndustryType, DesignStyle } from "@/types";

export interface StandardSizePreset {
  id: string;
  labelMeters: string;
  labelFeet: string;
  widthMeters: number;
  depthMeters: number;
  heightMeters: number;
  widthFeet: number;
  depthFeet: number;
  heightFeet: number;
  description: string;
  tag: string;
}

export const STANDARD_SIZES: StandardSizePreset[] = [
  {
    id: '3x3',
    labelMeters: '3 × 3 m',
    labelFeet: '10 × 10 ft',
    widthMeters: 3,
    depthMeters: 3,
    heightMeters: 3,
    widthFeet: 10,
    depthFeet: 10,
    heightFeet: 10,
    description: 'Standard single shell / linear kiosk booth (9 sqm / 100 sqft)',
    tag: 'Popular Compact',
  },
  {
    id: '3x6',
    labelMeters: '3 × 6 m',
    labelFeet: '10 × 20 ft',
    widthMeters: 6,
    depthMeters: 3,
    heightMeters: 3.5,
    widthFeet: 20,
    depthFeet: 10,
    heightFeet: 11.5,
    description: 'Wide frontal stall with high walkway visibility (18 sqm / 200 sqft)',
    tag: 'Standard Linear',
  },
  {
    id: '6x6',
    labelMeters: '6 × 6 m',
    labelFeet: '20 × 20 ft',
    widthMeters: 6,
    depthMeters: 6,
    heightMeters: 4,
    widthFeet: 20,
    depthFeet: 20,
    heightFeet: 13,
    description: 'Corner or island space with meeting lounge and video wall (36 sqm / 400 sqft)',
    tag: 'Executive Medium',
  },
  {
    id: '6x9',
    labelMeters: '6 × 9 m',
    labelFeet: '20 × 30 ft',
    widthMeters: 9,
    depthMeters: 6,
    heightMeters: 4.5,
    widthFeet: 30,
    depthFeet: 20,
    heightFeet: 15,
    description: 'Peninsula format with dual demo stations & hospitality counter (54 sqm / 600 sqft)',
    tag: 'Premium Peninsula',
  },
  {
    id: '9x9',
    labelMeters: '9 × 9 m',
    labelFeet: '30 × 30 ft',
    widthMeters: 9,
    depthMeters: 9,
    heightMeters: 5,
    widthFeet: 30,
    depthFeet: 30,
    heightFeet: 16.5,
    description: 'Large 4-side open island pavilion with conference room & hanging banner (81 sqm / 900 sqft)',
    tag: 'Flagship Island',
  },
  {
    id: '10x10',
    labelMeters: '10 × 10 m',
    labelFeet: '33 × 33 ft',
    widthMeters: 10,
    depthMeters: 10,
    heightMeters: 5.5,
    widthFeet: 33,
    depthFeet: 33,
    heightFeet: 18,
    description: 'Mega enterprise pavilion with mezzanine / double-decker capability (100 sqm / 1,089 sqft)',
    tag: 'Enterprise Mega',
  },
  {
    id: '12x12',
    labelMeters: '12 × 12 m',
    labelFeet: '40 × 40 ft',
    widthMeters: 12,
    depthMeters: 12,
    heightMeters: 6,
    widthFeet: 40,
    depthFeet: 40,
    heightFeet: 20,
    description: 'Grand convention centerpiece with immersive theatre & VIP suites (144 sqm / 1,600 sqft)',
    tag: 'Grand Centerpiece',
  },
  {
    id: 'custom',
    labelMeters: 'Custom Size',
    labelFeet: 'Custom Size',
    widthMeters: 8,
    depthMeters: 5,
    heightMeters: 4,
    widthFeet: 26,
    depthFeet: 16.5,
    heightFeet: 13,
    description: 'Define custom width, depth and permissible height limits',
    tag: 'Bespoke',
  },
];

export const OPEN_SIDES_OPTIONS: { value: OpenSides; label: string; iconName: string; description: string; walls: string }[] = [
  {
    value: '1_SIDE_INLINE',
    label: '1 Side Open (Inline / Linear)',
    iconName: 'Maximize',
    description: 'Front facing main aisle only. Enclosed with 3 solid/graphics walls on left, right, and rear.',
    walls: '3 Walls (Left, Right, Back)',
  },
  {
    value: '2_SIDES_CORNER',
    label: '2 Sides Open (Corner)',
    iconName: 'CornerUpRight',
    description: 'Located at junction of two intersecting walkways. 2 open sides with 2 back walls.',
    walls: '2 Walls (L-Shape Configuration)',
  },
  {
    value: '3_SIDES_PENINSULA',
    label: '3 Sides Open (Peninsula / End-Cap)',
    iconName: 'Columns',
    description: 'Prominent end-of-aisle location open on front, left, and right with 1 continuous rear back wall.',
    walls: '1 Rear Wall',
  },
  {
    value: '4_SIDES_ISLAND',
    label: '4 Sides Open (Island Pavilion)',
    iconName: 'Grid',
    description: '360° unobstructed walkthrough access from all four aisles. No mandatory perimeter walls.',
    walls: '0 Perimeter Walls (Free-standing)',
  },
];

export const STALL_TYPES: { value: StallType; label: string; badge: string; desc: string }[] = [
  {
    value: 'CUSTOM_WOODEN',
    label: 'Custom Wooden / MDF Build',
    badge: 'Luxury / Bespoke',
    desc: 'High-end timber framework, CNC milled curves, PU paint or laminate finish, integrated LED lighting.',
  },
  {
    value: 'MODULAR_OCTANORM',
    label: 'Modular Aluminum (Octanorm / Maxima)',
    badge: 'Eco / Reusable',
    desc: 'Lightweight structural aluminum extrusion with seamless graphic infills and quick assembly.',
  },
  {
    value: 'HYBRID_SYSTEM',
    label: 'Hybrid (Modular Framework + Custom Joinery)',
    badge: 'Cost-Effective',
    desc: 'Combines structural modular frame with customized feature counters, overhead branding, and feature walls.',
  },
  {
    value: 'DOUBLE_DECKER',
    label: 'Double Decker / Mezzanine Stall',
    badge: 'VIP Hospitality',
    desc: 'Engineered two-story steel structure with upper-deck VIP meeting lounge and lower-deck display floor.',
  },
  {
    value: 'FABRIC_TENSION',
    label: 'Seamless Fabric Tension System (SEG)',
    badge: 'Ultra Clean',
    desc: 'Edge-to-edge dye-sublimated backlit fabric graphics with invisible frame borders.',
  },
  {
    value: 'TRUSS_SYSTEM',
    label: 'Heavy Truss & Rigging Architecture',
    badge: 'Industrial High-Tech',
    desc: 'Heavy-duty aluminum box truss with motorized lighting hoists, moving heads, and suspended hanging rings.',
  },
];

export const INDUSTRIES: IndustryType[] = [
  'Technology & AI',
  'Real Estate & Property',
  'Healthcare & Pharma',
  'Automotive & Mobility',
  'Energy & Sustainability',
  'Finance & Fintech',
  'Food & Beverage',
  'Luxury & Jewelry',
  'Defense & Aerospace',
  'General Exhibition',
];

export const DESIGN_STYLES: { name: DesignStyle; desc: string; colors: string[] }[] = [
  {
    name: 'Ultra-Modern Minimalist',
    desc: 'Clean architectural lines, floating counters, stark whites, warm ambient backlighting.',
    colors: ['#FFFFFF', '#0F172A', '#0284C7'],
  },
  {
    name: 'Futuristic High-Tech LED',
    desc: 'P3/P2.5 LED video walls, neon edge lighting, dark cybernetic accents, interactive glass.',
    colors: ['#030712', '#38BDF8', '#818CF8'],
  },
  {
    name: 'Warm Wood & Biophilic',
    desc: 'Natural oak slats, live preserved moss walls, acoustic warm lighting, organic curves.',
    colors: ['#78350F', '#15803D', '#FDFBF7'],
  },
  {
    name: 'Industrial Truss & Metal',
    desc: 'Exposed matte black trussing, raw steel finishes, theatrical spotlighting, high impact.',
    colors: ['#1E293B', '#F59E0B', '#64748B'],
  },
  {
    name: 'Luxury Sleek & Glossy',
    desc: 'High-gloss acrylics, brushed gold titanium trims, marble vinyl floor, velvet lounge.',
    colors: ['#D97706', '#18181B', '#F8FAFC'],
  },
  {
    name: 'Bold Vibrant Experiential',
    desc: 'High saturation brand colors, curved photo-op arches, gamified interactive kiosk zones.',
    colors: ['#EC4899', '#8B5CF6', '#3B82F6'],
  },
  {
    name: 'Corporate Executive',
    desc: 'Subdued corporate navy/slate, soundproofed glass boardroom, reception podium.',
    colors: ['#075985', '#334155', '#E2E8F0'],
  },
];

export const FUNCTIONAL_ZONES = [
  { id: 'reception', label: 'Reception & Lead Capture Counter', icon: 'UserCheck' },
  { id: 'vip_lounge', label: 'VIP Lounge & Coffee Bar', icon: 'Coffee' },
  { id: 'meeting_room', label: 'Enclosed Private Meeting Room', icon: 'Users' },
  { id: 'led_wall', label: 'Seamless LED Video Wall Screen', icon: 'Tv' },
  { id: 'demo_pods', label: 'Interactive Product Demo Pods', icon: 'Layers' },
  { id: 'storage_pantry', label: 'Lockable Storage & Hospitality Pantry', icon: 'Box' },
  { id: 'hanging_banner', label: 'Overhead Suspended Ceiling Ring/Fascia', icon: 'ArrowUpCircle' },
  { id: 'touchscreen_kiosk', label: 'Digital Touchscreen Information Kiosks', icon: 'Tablet' },
  { id: 'display_pedestals', label: 'Illuminated Acrylic Display Pedestals', icon: 'Shield' },
];

export const DEMO_USERS: User[] = [
  {
    id: 'user-superadmin',
    name: 'Alexander Sterling',
    email: 'alexander@expocraft.io',
    role: 'SUPER_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    company: 'ExpoCraft Global HQ',
    phone: '+971 50 123 4567',
  },
  {
    id: 'user-admin',
    name: 'Marcus Vance',
    email: 'marcus.vance@expocraft.io',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    company: 'ExpoCraft Operations',
    phone: '+1 (415) 880-9210',
  },
  {
    id: 'user-designer',
    name: 'Elena Rostova',
    email: 'elena.design@expocraft.io',
    role: 'DESIGNER',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    company: '3D Spatial Design Lab',
    phone: '+44 20 7946 0912',
  },
  {
    id: 'user-estimator',
    name: 'Tariq Al-Mansoor',
    email: 'tariq.boq@expocraft.io',
    role: 'ESTIMATOR',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    company: 'Commercial & Costing Dept',
    phone: '+971 55 987 6543',
  },
  {
    id: 'user-sales',
    name: 'Sophia Chen',
    email: 'sophia.sales@expocraft.io',
    role: 'SALES',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    company: 'Global Client Partnerships',
    phone: '+1 (212) 555-0199',
  },
  {
    id: 'user-client',
    name: 'David K. Hoffman (VP Marketing)',
    email: 'david.hoffman@novatech-ai.com',
    role: 'CLIENT',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    company: 'NovaTech AI Global',
    phone: '+1 (650) 432-1000',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    projectCode: 'EXP-2026-001',
    name: 'NovaTech AI Experience Pavilion',
    status: 'QUOTATION_GENERATED',
    createdAt: '2026-09-10T09:30:00Z',
    updatedAt: '2026-09-18T14:20:00Z',
    assignedDesigner: 'Elena Rostova',
    assignedEstimator: 'Tariq Al-Mansoor',
    assignedSales: 'Sophia Chen',
    client: {
      id: 'client-001',
      companyName: 'NovaTech AI Systems Inc.',
      contactPerson: 'David K. Hoffman',
      email: 'david.hoffman@novatech-ai.com',
      phone: '+1 (650) 432-1000',
      website: 'https://novatech-ai.com',
      country: 'United States',
      city: 'San Francisco',
      vatNumber: 'US-948271049',
    },
    exhibition: {
      exhibitionName: 'GITEX GLOBAL 2026',
      venue: 'Dubai World Trade Centre (DWTC)',
      city: 'Dubai',
      country: 'United Arab Emirates',
      hallNumber: 'Hall 7 (Artificial Intelligence Hall)',
      stallNumber: 'Stand H7-B20',
      startDate: '2026-10-12',
      endDate: '2026-10-16',
      moveInDate: '2026-10-09',
      moveOutDate: '2026-10-17',
    },
    dimensions: {
      unit: 'METERS',
      width: 9,
      depth: 9,
      height: 5,
      maxHeightLimit: 6,
      totalAreaSqm: 81,
      totalAreaSqft: 871.88,
      openSides: '4_SIDES_ISLAND',
      stallType: 'CUSTOM_WOODEN',
    },
    brief: {
      industry: 'Technology & AI',
      designStyle: 'Futuristic High-Tech LED',
      primaryColor: '#0284C7',
      secondaryColor: '#0F172A',
      brandGuidelinesUrl: 'https://brand.novatech-ai.com',
      functionalZones: ['Reception', 'LED Wall', 'VIP Lounge', 'Interactive Demo Stations', 'Storage Room', 'Hanging Ring'],
      specialRequirements: 'Must feature a curved 3.5m tall P2.6 LED screen with live AI generative graphics showcase and lockable soundproof boardroom.',
      hasLedScreen: true,
      hasPantryStorage: true,
      hasReceptionCounter: true,
      hasHangingBanner: true,
      productDisplaysCount: 4,
      meetingRoomsCount: 1,
    },
    budget: {
      currency: 'USD',
      targetBudgetMin: 85000,
      targetBudgetMax: 110000,
      targetMarginPercent: 28,
      clientBudgetStated: 95000,
      paymentTerms: '50% Advance, 40% On Build Handover, 10% Post Event',
    },
    designConcepts: [
      {
        id: 'dc-001',
        title: 'CyberLoom Island Concept V3',
        version: 3,
        thumbnailUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
        highResUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1600&auto=format&fit=crop&q=80',
        aiPromptUsed: 'Ultra-modern 9x9m 4-side open island exhibition stall, curved black timber arches with neon blue illumination, 6m wide P2.5 curved LED wall, VIP meeting room with smart privacy glass, 3D hanging cubic halo, ultra clean epoxy white flooring, photorealistic 8k octane render.',
        isClientApproved: true,
        createdAt: '2026-09-14T11:00:00Z',
        views: {
          front: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
          isometric: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop&q=80',
        }
      }
    ],
    boqItems: [
      {
        id: 'boq-001',
        category: 'FLOORING',
        itemCode: 'FL-01',
        name: 'Raised Wooden Platform 100mm with High-Gloss White Acrylic Finish',
        description: '100mm heavy duty structural subfloor with ramped aluminum edging and cable trenches.',
        unit: 'sqm',
        quantity: 81,
        unitCost: 75,
        subtotal: 6075,
        markupPercent: 30,
        clientRate: 97.5,
        totalClientPrice: 7897.5,
      },
      {
        id: 'boq-002',
        category: 'WALLS_PARTITIONS',
        itemCode: 'WL-04',
        name: 'Custom Curved MDF Architectural Feature Wall (H: 4.8m)',
        description: 'Double sided fire-retardant MDF skeleton with matte polyurethane spray paint finish.',
        unit: 'sqm',
        quantity: 58,
        unitCost: 195,
        subtotal: 11310,
        markupPercent: 32,
        clientRate: 257.4,
        totalClientPrice: 14929.2,
      },
      {
        id: 'boq-003',
        category: 'FURNITURE_AV',
        itemCode: 'AV-01',
        name: 'P2.6 High Refresh Rate Indoor LED Video Wall (6m x 3m)',
        description: 'Rental for 5 days exhibition including 4K video processor, rigging and onsite technician.',
        unit: 'sqm',
        quantity: 18,
        unitCost: 650,
        subtotal: 11700,
        markupPercent: 25,
        clientRate: 812.5,
        totalClientPrice: 14625,
      },
      {
        id: 'boq-004',
        category: 'FASCIA_CEILING',
        itemCode: 'CL-02',
        name: 'Circular Hanging Banner Truss Structure 5m Dia with Backlit Fabric',
        description: 'Suspended aluminum box truss ring with motor hoists, safety cables, and DWTC rigging approval.',
        unit: 'set',
        quantity: 1,
        unitCost: 6200,
        subtotal: 6200,
        markupPercent: 35,
        clientRate: 8370,
        totalClientPrice: 8370,
      },
      {
        id: 'boq-005',
        category: 'LABOUR_LOGISTICS',
        itemCode: 'LB-01',
        name: 'Turnkey Fabrication, Site Rigging, Installation & Teardown Crew',
        description: 'Master carpenters, certified electricians, painters and supervisors 24/7 during setup.',
        unit: 'lump sum',
        quantity: 1,
        unitCost: 14500,
        subtotal: 14500,
        markupPercent: 20,
        clientRate: 17400,
        totalClientPrice: 17400,
      }
    ],
    quotations: [
      {
        id: 'quot-001',
        quotationNumber: 'QT-2026-081-V2',
        version: 2,
        issueDate: '2026-09-16',
        validUntil: '2026-10-01',
        subtotalCost: 63221.7,
        overheadMargin: 12644.34,
        discountAmount: 2500,
        vatPercent: 5,
        vatAmount: 3668.3,
        grandTotal: 77034.34,
        currency: 'USD',
        status: 'SENT',
        clientNotes: 'Quotation includes full turnkey DWTC safety approvals, overnight rigging, and dedicated AV technician during show hours.',
      }
    ],
    activityLogs: [
      {
        id: 'act-1',
        timestamp: '2026-09-10T09:30:00Z',
        actor: 'David K. Hoffman',
        role: 'CLIENT',
        action: 'Brief Submitted',
        details: 'Initial requirements for GITEX 2026 Island booth submitted.',
      },
      {
        id: 'act-2',
        timestamp: '2026-09-14T11:00:00Z',
        actor: 'Elena Rostova',
        role: 'DESIGNER',
        action: 'AI 3D Concept V3 Generated',
        details: 'Generated 4 photorealistic views with curved LED wall configuration.',
      },
      {
        id: 'act-3',
        timestamp: '2026-09-16T15:40:00Z',
        actor: 'Tariq Al-Mansoor',
        role: 'ESTIMATOR',
        action: 'BOQ & Quotation V2 Published',
        details: 'Updated LED screen pricing and confirmed rigging labor costs.',
      }
    ]
  },
  {
    id: 'proj-002',
    projectCode: 'EXP-2026-002',
    name: 'AeroDynamics Hypersonic Pavilion',
    status: 'DESIGN_READY',
    createdAt: '2026-09-12T14:15:00Z',
    updatedAt: '2026-09-17T18:00:00Z',
    assignedDesigner: 'Elena Rostova',
    assignedEstimator: 'Tariq Al-Mansoor',
    assignedSales: 'Sophia Chen',
    client: {
      id: 'client-002',
      companyName: 'AeroDynamics Defense Group',
      contactPerson: 'Sir Julian Sterling',
      email: 'j.sterling@aerodynamics.co.uk',
      phone: '+44 20 7946 0192',
      country: 'United Kingdom',
      city: 'London',
      vatNumber: 'GB-192837465',
    },
    exhibition: {
      exhibitionName: 'Farnborough International Airshow 2026',
      venue: 'Farnborough Exhibition Centre',
      city: 'Farnborough',
      country: 'United Kingdom',
      hallNumber: 'Hall 4',
      stallNumber: 'Stand 4-C12',
      startDate: '2026-07-20',
      endDate: '2026-07-24',
      moveInDate: '2026-07-16',
      moveOutDate: '2026-07-25',
    },
    dimensions: {
      unit: 'METERS',
      width: 6,
      depth: 6,
      height: 4,
      maxHeightLimit: 4.5,
      totalAreaSqm: 36,
      totalAreaSqft: 387.5,
      openSides: '2_SIDES_CORNER',
      stallType: 'HYBRID_SYSTEM',
    },
    brief: {
      industry: 'Defense & Aerospace',
      designStyle: 'Industrial Truss & Metal',
      primaryColor: '#1E293B',
      secondaryColor: '#F59E0B',
      functionalZones: ['Reception', 'Touchscreen Kiosks', 'Meeting Room', 'Storage Room'],
      specialRequirements: 'Full scale missile mock-up display plinth and secure access control meeting room.',
      hasLedScreen: true,
      hasPantryStorage: true,
      hasReceptionCounter: true,
      hasHangingBanner: false,
    },
    budget: {
      currency: 'GBP',
      targetBudgetMin: 45000,
      targetBudgetMax: 60000,
      targetMarginPercent: 30,
      clientBudgetStated: 52000,
    },
    designConcepts: [
      {
        id: 'dc-002',
        title: 'Titanium Stealth Corner',
        version: 1,
        thumbnailUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop&q=80',
        isClientApproved: false,
        createdAt: '2026-09-17T18:00:00Z',
        views: {
          front: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop&q=80',
        }
      }
    ],
    boqItems: [],
    quotations: [],
    activityLogs: [
      {
        id: 'act-201',
        timestamp: '2026-09-12T14:15:00Z',
        actor: 'Sir Julian Sterling',
        role: 'CLIENT',
        action: 'Brief Created',
        details: 'Corner stand specification for Farnborough Airshow.',
      }
    ]
  },
  {
    id: 'proj-003',
    projectCode: 'EXP-2026-003',
    name: 'BioGenix Regenerative Medicine Stand',
    status: 'BRIEF_RECEIVED',
    createdAt: '2026-09-18T08:00:00Z',
    updatedAt: '2026-09-18T10:15:00Z',
    assignedDesigner: 'Elena Rostova',
    assignedSales: 'Sophia Chen',
    client: {
      id: 'client-003',
      companyName: 'BioGenix Therapeutics AG',
      contactPerson: 'Dr. Clara Zimmerman',
      email: 'c.zimmerman@biogenix.de',
      phone: '+49 89 1234 5678',
      country: 'Germany',
      city: 'Munich',
      vatNumber: 'DE-837461920',
    },
    exhibition: {
      exhibitionName: 'MEDICA 2026',
      venue: 'Messe Düsseldorf',
      city: 'Düsseldorf',
      country: 'Germany',
      hallNumber: 'Hall 3',
      stallNumber: 'Stand 3-F45',
      startDate: '2026-11-16',
      endDate: '2026-11-19',
      moveInDate: '2026-11-13',
      moveOutDate: '2026-11-20',
    },
    dimensions: {
      unit: 'METERS',
      width: 3,
      depth: 6,
      height: 3.5,
      maxHeightLimit: 4,
      totalAreaSqm: 18,
      totalAreaSqft: 193.75,
      openSides: '1_SIDE_INLINE',
      stallType: 'FABRIC_TENSION',
    },
    brief: {
      industry: 'Healthcare & Pharma',
      designStyle: 'Warm Wood & Biophilic',
      primaryColor: '#10B981',
      secondaryColor: '#FFFFFF',
      functionalZones: ['Reception', 'VIP Lounge', 'Storage Room'],
      specialRequirements: 'Biophilic preserved green wall with backlit LED logo and recycled wood display podiums.',
      hasLedScreen: false,
      hasPantryStorage: true,
      hasReceptionCounter: true,
      hasHangingBanner: false,
    },
    budget: {
      currency: 'EUR',
      targetBudgetMin: 22000,
      targetBudgetMax: 30000,
      targetMarginPercent: 25,
      clientBudgetStated: 25000,
    },
    designConcepts: [],
    boqItems: [],
    quotations: [],
    activityLogs: [
      {
        id: 'act-301',
        timestamp: '2026-09-18T08:00:00Z',
        actor: 'Sophia Chen',
        role: 'SALES',
        action: 'New Project Brief Created',
        details: 'Client confirmed stand space allocation at Messe Düsseldorf.',
      }
    ]
  }
];

export const MARKET_RATES_DATA = [
  {
    category: 'Flooring',
    item: 'Raised Platform 100mm with Acrylic/Vinyl',
    unit: 'sqm',
    rates: { Dubai: 75, Riyadh: 85, LasVegas: 120, London: 95, Frankfurt: 90 },
    currency: 'USD',
  },
  {
    category: 'Walls & Structure',
    item: 'MDF Custom Spray-Painted Partition Wall',
    unit: 'sqm',
    rates: { Dubai: 195, Riyadh: 210, LasVegas: 290, London: 240, Frankfurt: 230 },
    currency: 'USD',
  },
  {
    category: 'Walls & Structure',
    item: 'Seamless Backlit Fabric Tension System (SEG)',
    unit: 'sqm',
    rates: { Dubai: 140, Riyadh: 155, LasVegas: 220, London: 175, Frankfurt: 165 },
    currency: 'USD',
  },
  {
    category: 'Audio Visual',
    item: 'P2.6 Indoor Ultra-Fine LED Screen Rental',
    unit: 'sqm / day',
    rates: { Dubai: 130, Riyadh: 145, LasVegas: 250, London: 180, Frankfurt: 170 },
    currency: 'USD',
  },
  {
    category: 'Ceiling & Rigging',
    item: 'Overhead Circular Truss Hanging Banner (5m Dia)',
    unit: 'per unit',
    rates: { Dubai: 6200, Riyadh: 6800, LasVegas: 9500, London: 7400, Frankfurt: 7100 },
    currency: 'USD',
  },
  {
    category: 'Labour & Craftsmanship',
    item: 'Master Exhibition Carpenter (Day Rate 10hr)',
    unit: 'day',
    rates: { Dubai: 180, Riyadh: 190, LasVegas: 650, London: 450, Frankfurt: 420 },
    currency: 'USD',
  },
  {
    category: 'Labour & Craftsmanship',
    item: 'Certified Rigging & AV Technician (Day Rate)',
    unit: 'day',
    rates: { Dubai: 260, Riyadh: 280, LasVegas: 800, London: 550, Frankfurt: 500 },
    currency: 'USD',
  },
];
