import { MarketRateEntry } from "@/types/boq";

export const VERIFIED_MARKET_RATES: MarketRateEntry[] = [
  {
    id: "mr-1",
    category: "Structure",
    materialOrService: "Structural Timber Stud Framing (H: 3-5m)",
    unit: "sqm",
    country: "United Arab Emirates",
    city: "Dubai",
    supplier: "DWTC Approved Joinery Contractors",
    qualityGrade: "Commercial",
    baseRate: 48,
    labourRate: 22,
    currency: "USD",
    effectiveDate: "2026-09-01",
    confidenceScore: 98,
    confidenceLevel: "VERIFIED_SUPPLIER",
    notes: "Verified rate from 4 active DWTC Q3 2026 tenders.",
  },
  {
    id: "mr-2",
    category: "Structure",
    materialOrService: "Structural Timber Stud Framing (H: 3-5m)",
    unit: "sqm",
    country: "Saudi Arabia",
    city: "Riyadh",
    supplier: "Riyadh Front Exhibition Builders",
    qualityGrade: "Commercial",
    baseRate: 54,
    labourRate: 25,
    currency: "USD",
    effectiveDate: "2026-08-15",
    confidenceScore: 95,
    confidenceLevel: "VERIFIED_SUPPLIER",
    notes: "Riyadh Front & LEAP 2026 contractor benchmark.",
  },
  {
    id: "mr-3",
    category: "MDF/Plywood",
    materialOrService: "18mm Fire-Retardant MDF Sheeting (Class 0)",
    unit: "sqm",
    country: "United Arab Emirates",
    city: "Dubai",
    supplier: "National Timber & Wood Supplies",
    qualityGrade: "Premium High-Gloss",
    baseRate: 36,
    labourRate: 14,
    currency: "USD",
    effectiveDate: "2026-09-10",
    confidenceScore: 96,
    confidenceLevel: "VERIFIED_SUPPLIER",
  },
  {
    id: "mr-4",
    category: "Aluminum",
    materialOrService: "Modular Anodized Aluminum Extrusion (Octanorm / Maxima)",
    unit: "lm",
    country: "Germany",
    city: "Frankfurt",
    supplier: "Messe Frankfurt Systems GmbH",
    qualityGrade: "Commercial",
    baseRate: 38,
    labourRate: 20,
    currency: "EUR",
    effectiveDate: "2026-09-05",
    confidenceScore: 97,
    confidenceLevel: "VERIFIED_SUPPLIER",
  },
  {
    id: "mr-5",
    category: "Flooring",
    materialOrService: "100mm Raised Floor with High-Gloss Acrylic Finish",
    unit: "sqm",
    country: "United Arab Emirates",
    city: "Dubai",
    supplier: "FloorCraft UAE",
    qualityGrade: "Premium High-Gloss",
    baseRate: 55,
    labourRate: 20,
    currency: "USD",
    effectiveDate: "2026-09-12",
    confidenceScore: 98,
    confidenceLevel: "VERIFIED_SUPPLIER",
  },
  {
    id: "mr-6",
    category: "Flooring",
    materialOrService: "100mm Raised Floor with High-Gloss Acrylic Finish",
    unit: "sqm",
    country: "United States",
    city: "Las Vegas",
    supplier: "Las Vegas Convention Rigging & Floor",
    qualityGrade: "Premium High-Gloss",
    baseRate: 95,
    labourRate: 45,
    currency: "USD",
    effectiveDate: "2026-08-20",
    confidenceScore: 94,
    confidenceLevel: "VERIFIED_SUPPLIER",
    notes: "Union labor rates applied.",
  },
  {
    id: "mr-7",
    category: "Printing",
    materialOrService: "Seamless Backlit SEG Fabric (210gsm Samba)",
    unit: "sqm",
    country: "United Kingdom",
    city: "London",
    supplier: "ExCeL London Graphics Group",
    qualityGrade: "Premium High-Gloss",
    baseRate: 42,
    labourRate: 15,
    currency: "GBP",
    effectiveDate: "2026-09-08",
    confidenceScore: 96,
    confidenceLevel: "VERIFIED_SUPPLIER",
  },
  {
    id: "mr-8",
    category: "AV",
    materialOrService: "P2.6 High Refresh Rate Indoor LED Video Wall",
    unit: "sqm",
    country: "United Arab Emirates",
    city: "Dubai",
    supplier: "Creative Technology / DWTC AV",
    qualityGrade: "Premium High-Gloss",
    baseRate: 480,
    labourRate: 150,
    currency: "USD",
    effectiveDate: "2026-09-14",
    confidenceScore: 99,
    confidenceLevel: "VERIFIED_SUPPLIER",
    notes: "5-day exhibition rental including 4K video processor & standby technician.",
  },
  {
    id: "mr-9",
    category: "Installation",
    materialOrService: "Master Exhibition Carpenter (Day Rate 10hr)",
    unit: "day",
    country: "United Arab Emirates",
    city: "Dubai",
    supplier: "DWTC Licensed Labour Guild",
    qualityGrade: "Commercial",
    baseRate: 180,
    labourRate: 0,
    currency: "USD",
    effectiveDate: "2026-09-01",
    confidenceScore: 98,
    confidenceLevel: "VERIFIED_SUPPLIER",
  },
  {
    id: "mr-10",
    category: "Installation",
    materialOrService: "Master Exhibition Carpenter (Day Rate 10hr)",
    unit: "day",
    country: "United States",
    city: "Las Vegas",
    supplier: "IATSE Union Local 720",
    qualityGrade: "Commercial",
    baseRate: 650,
    labourRate: 0,
    currency: "USD",
    effectiveDate: "2026-08-01",
    confidenceScore: 99,
    confidenceLevel: "VERIFIED_SUPPLIER",
  },
];
